# Generated by Django 4.2.5 on 2023-10-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='john doe', max_length=100)),
                ('number', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('image', models.ImageField(default='profiles/default.jpg', upload_to='images')),
            ],
        ),
    ]
