# Generated by Django 4.2.5 on 2023-10-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='john doe', max_length=100)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(default='C1', max_length=2)),
            ],
        ),
    ]
